import {library} from '@fortawesome/fontawesome-svg-core';
import {
    faInfoCircle,
    faEdit,
    faTrashAlt,
    faSearch,
    faSync,
    faArrowLeft,
    faUndo,
    faSave,
    faTrash,
    faPlus,
    faMapMarkedAlt,
    faThList,
    faPlusCircle,
    faBuilding,
    faTachometerAlt,
    faCogs,
    faFolderOpen,
    faTasks,
    faHandshake,
    faUser,
    faSignOutAlt,
    faKey,
    faHome,
    faChartLine,
    faUsers,
    faCalendarAlt,
    faCommentDots,
    faBars,
    faTimes,
} from '@fortawesome/free-solid-svg-icons';

library.add(faInfoCircle, faEdit, faTrashAlt, faSearch, faSync, faArrowLeft, faUndo, faSave, faTrash, faPlus, faMapMarkedAlt, faThList, faPlusCircle, faBuilding, faTachometerAlt, faCogs, faFolderOpen, faTasks, faHandshake, faUser, faSignOutAlt, faKey, faHome, faChartLine, faUsers, faCalendarAlt, faCommentDots, faBars, faTimes);
