management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

jwt:
  secret-key: e7a2f7c23966b7b076f8719c0407857ab8d3976d4a12df232229c872d98d4fde